use_frameworks!

platform :ios, '10.0'

target 'ZLLayoutButton_Example' do
  pod 'ZLLayoutButton', :path => '../'

  target 'ZLLayoutButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
